# Generated by Django 3.0.4 on 2020-04-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('name', models.TextField(max_length=40)),
                ('city', models.TextField(max_length=40)),
            ],
        ),
    ]
