# Generated by Django 3.0.4 on 2020-04-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
