# Generated by Django 3.0.4 on 2020-04-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0003_auto_20200425_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlist',
            options={'verbose_name': 'ItemList', 'verbose_name_plural': 'ItemLists'},
        ),
    ]
