# Generated by Django 3.0.8 on 2020-07-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmpassword',
            new_name='currentPassword',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='newPassword',
        ),
    ]
