# Generated by Django 3.0.8 on 2020-07-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='type',
        ),
    ]
