# Generated by Django 3.0.8 on 2020-07-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='correlation',
            field=models.CharField(max_length=40),
        ),
    ]
